services:
  api:
    build: ./webapp
    container_name: fastapi_backend
    env_file:
      - .env
    volumes:
      - ./webapp:/app
    ports:
      - "80:80"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  db:
    image: postgres:15
    container_name: wikirooms-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./webapp/database/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
