"""Add room_id to BookLink and make book_id nullable

Revision ID: 1785d774e617
Revises: f1aac3fcecc7
Create Date: 2025-11-05 15:26:00.888485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1785d774e617'
down_revision: Union[str, None] = 'f1aac3fcecc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_links', sa.Column('room_id', sa.Integer(), nullable=False))
    op.alter_column('book_links', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_book_links_room_id', 'book_links', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_book_links_room_id', 'book_links', type_='foreignkey')
    op.alter_column('book_links', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('book_links', 'room_id')
    # ### end Alembic commands ###
