"""remove index

Revision ID: 4f693eba4505
Revises: b946af56bcbe
Create Date: 2025-12-21 14:46:21.718149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f693eba4505'
down_revision: Union[str, None] = 'b946af56bcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_links_link_key'), 'book_links', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('book_links_link_key'), 'book_links', ['link'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
