"""add groups and user-group relation

Revision ID: 8929ed7017aa
Revises: c1b40bb2ef00
Create Date: 2026-01-31 10:37:04.758426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8929ed7017aa'
down_revision: Union[str, None] = 'c1b40bb2ef00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.add_column('data_users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data_users', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_users', type_='foreignkey')
    op.drop_column('data_users', 'group_id')
    op.drop_table('groups')
    # ### end Alembic commands ###
