"""empty message

Revision ID: 8cf131584066
Revises: 8929ed7017aa
Create Date: 2026-01-31 11:59:31.652875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf131584066'
down_revision: Union[str, None] = '8929ed7017aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('data_users_group_id_fkey'), 'data_users', type_='foreignkey')
    op.drop_column('data_users', 'group_id')
    op.add_column('user_sessions', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_sessions', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_column('user_sessions', 'group_id')
    op.add_column('data_users', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('data_users_group_id_fkey'), 'data_users', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
