"""rename

Revision ID: 9cc7871578fd
Revises: 51345ce39c00
Create Date: 2025-05-17 18:45:30.567475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc7871578fd'
down_revision: Union[str, None] = '51345ce39c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('token', sa.String(), nullable=False))
    op.drop_column('api_keys', 'secret')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('api_keys', sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('api_keys', 'token')
    # ### end Alembic commands ###
