"""refactor entities

Revision ID: f1aac3fcecc7
Revises: c4a5b40695de
Create Date: 2025-11-03 15:58:39.246610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1aac3fcecc7'
down_revision: Union[str, None] = 'c4a5b40695de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_user_id'], ['data_users.id'], name='fk_user_sessions_data_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_session_id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_book_session_events_book_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_session_id'], ['user_sessions.id'], name='fk_book_session_events_user_session_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book_links', sa.Column('user_session_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('book_links_room_id_fkey'), 'book_links', type_='foreignkey')
    op.create_foreign_key('fk_book_links_user_session_id', 'book_links', 'user_sessions', ['user_session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('book_links', 'room_id')
    op.drop_column('books', 'close_time')
    op.drop_column('books', 'open_time')
    op.add_column('rooms', sa.Column('user_session_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('rooms_next_room_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_constraint(op.f('rooms_previous_room_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_constraint(op.f('rooms_data_user_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key('fk_rooms_user_session_id', 'rooms', 'user_sessions', ['user_session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rooms', 'previous_room_id')
    op.drop_column('rooms', 'data_user_id')
    op.drop_column('rooms', 'link_id')
    op.drop_column('rooms', 'next_room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('next_room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('data_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('previous_room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_rooms_user_session_id', 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_data_user_id_fkey'), 'rooms', 'data_users', ['data_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('rooms_previous_room_id_fkey'), 'rooms', 'rooms', ['previous_room_id'], ['id'])
    op.create_foreign_key(op.f('rooms_next_room_id_fkey'), 'rooms', 'rooms', ['next_room_id'], ['id'])
    op.drop_column('rooms', 'user_session_id')
    op.add_column('books', sa.Column('open_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('close_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('book_links', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_book_links_user_session_id', 'book_links', type_='foreignkey')
    op.create_foreign_key(op.f('book_links_room_id_fkey'), 'book_links', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('book_links', 'user_session_id')
    op.drop_table('book_session_events')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
